# Generated by Django 4.1.7 on 2023-03-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evoting_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='voter_id',
        ),
    ]
